
const CONSTANT = {
    LOGIN_DATA: 'LOGIN_DATA',
    DATA_ERROR: 'DATA_ERROR',
    DATA_SUCCESS: 'DATA_SUCCESS',

    OTP_DATA: 'OTP_DATA',
    OTP_DATA_ERROR: 'OTP_DATA_ERROR',
    OTP_DATA_SUCCESS: 'OTP_DATA_SUCCESS',

    Resend_OTP_DATA: 'Resend_OTP_DATA',
    Resend_OTP_DATA_ERROR: 'Resend_OTP_DATA_ERROR',
    Resend_OTP_DATA_SUCCESS: 'Resend_OTP_DATA_SUCCESS',

}

export { CONSTANT }