
const CONSTANT = {
    LOGIN_DATA: 'LOGIN_DATA',
    DATA_ERROR: 'DATA_ERROR',
    DATA_SUCCESS: 'DATA_SUCCESS',
    
    STORE_LOCATION_DATA:'STORE_LOCATION_DATA',
    STORE_ERROR:'STORE_ERROR',
    STORE_SUCCESS:'STORE_SUCCESS',
    ACCESS_TOKEN:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTQ3NzU3MTIsImRhdGEiOnsiaWQiOjUxMSwibW9iaWxlX251bWJlciI6Ijg3NTA4NzI5OTAiLCJuYW1lIjoiVG9ueSIsInJvbGVfaWQiOjEsImlzX3NpX3VzZXIiOjB9LCJpYXQiOjE2NTQxNzA5MTJ9.tGk2hwAQktTZFcDH0JCo1nz1yiezTqT8cCjC8olkEOk'

}

export { CONSTANT }