import {StyleSheet} from 'react-native';

import fontfaimly from '../../utility/Font-Declarations';

export default StyleSheet.create({
  validity: {
    width: 156,
    height: 50,
    borderRadius: 8,
    borderColor: '#C3C7D9',
    borderWidth: 0.5,
    justifyContent: 'center',
    padding: 10,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageStyle: {
    width: 100,
    height: 100,
    alignItems: 'stretch',
  },
  offerdisclaimerinputtex: {
    height: 100,
    borderWidth: 0.5,
    borderRadius: 8,
    borderColor: '#C3C7D9',
    fontFamily: fontfaimly.Poppins,
    padding: 10,
    paddingTop: 10,
    fontSize: 12,
    color: '#657180',
  },
  offerdisclimerLabelText: {
    paddingBottom: 10,
    fontSize: 14,
    color: '#657180',
    fontFamily: fontfaimly.Alte_DIN,
  },
  addPostMeassgInputText: {
    height: 100,
    borderWidth: 0.5,
    borderRadius: 8,
    borderColor: '#C3C7D9',
    fontFamily: fontfaimly.Poppins,
    padding: 10,
    paddingTop: 10,
    fontSize: 12,
    color: '#657180',
  },
  addPostMessageLabelText: {
    paddingTop: 24,
    paddingBottom: 10,
    fontSize: 14,
    color: '#657180',
    fontFamily: fontfaimly.Alte_DIN,
  },
  OfferLinkInputText: {
    height: 50,
    borderWidth: 0.5,
    borderRadius: 8,
    borderColor: '#C3C7D9',
    color: '#5F6368',
    fontSize: 12,
    fontFamily: fontfaimly.Poppins,
    padding: 10,
  },
  CouponCodeInputText: {
    height: 50,
    borderWidth: 0.5,
    borderRadius: 8,
    borderColor: '#C3C7D9',
    backgroundColor: 'white',
    fontFamily: fontfaimly.Poppins,
    padding: 10,
    paddingTop: 10,
    fontSize: 12,
    color: '#657180',
  },
  CouponCodeLabelText: {
    paddingTop: 24,
    paddingBottom: 10,
    fontSize: 14,
    color: '#657180',
    fontFamily: fontfaimly.Alte_DIN,
  },
  LinktoOfferLabelText: {
    fontSize: 14,
    color: '#657180',
    fontFamily: fontfaimly.Alte_DIN,
    paddingTop: 24,
    paddingBottom: 15,
  },
  LocationLabelText: {
    paddingBottom: 10,
    fontSize: 14,
    color: '#657180',
    fontFamily: fontfaimly.Alte_DIN,
  },
  addPostImageView: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 30,
    backgroundColor: 'rgba(247, 252, 255, 1)',
  },
});
