require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'
target 'ConnectMobileApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  target 'ConnectMobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

#  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' }, configurations: ['debug', 'release'])  #    flipper_post_install(installer)
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
   use_flipper!()
#  use_frameworks! :linkage => :static

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

#target 'SiConnectNotification' do
#  pod 'Firebase/Messaging' # eg 6.31.0
#end
